# install docker and module dependacies (done)
# download image docker (done)
# deploy container from existing image (done)
# list active container (done still list one active container)
# delete container (done)

---
- name: docker installation and management
  hosts: local
  become: true
  vars_files:
    - default_var.yaml
  tasks:
    - name: check connection
      ping:
    - name: update centos
      yum:
        name: '*'
        state: latest
    - name: install pip requirements
      yum:
        name: epel-release
        state: latest
    - name: install pip
      yum:
        name: python-pip
        state: latest
    - name: install docker module
      pip:
        name: docker
    - name: install docker
      yum:
        name: docker
        state: latest
    - name: download docker image
      docker_image:
        name: '{{ container_image }}'
        source: pull
    - name: Create a container
      docker_container:
        name: web
        state: started
        image: nginx
        published_ports: 80:80
    # module for inspect docker container
    - name: get info from my container
      docker_container_info:
        name: '{{ container }}'
      register: hasil # input result to variable hasil
    - name: Does container exist?
      debug:
        msg: "The container {{ 'exists' if hasil.exists else 'does not exist' }}"
    - name: show list of running container
      debug:
        var: hasil.container
      when: hasil.exists
      # delete docker container
    - name: delete container
      docker_container:
        name: '{{ delete_container }}'
        state: absent
        
